---
title: "Lab 6 Black Swans"
author: "Erik Svenneby, Jorge Robelo, Mandy Karako, Ryan Bilkie, Thorbin Atwell"
date: "10/1/2019"
output: html_document
---

```{r}
COflights <- read_csv("https://files.osf.io/v1/resources/3z5as4pej8/providers/osfstorage/5a8ca28f57103100104584db")
```
## Thorbin's Declaration: How does seasonal weather (month) affect the punctuality of flights? 



##jorge raw code, there are significant differences in arrival to DEN when looking at individual months. There are no significant differences in whether a flight arrived early or late in relation with the distance traveled
```{r}
#Note: the DIA manangers do not care about flights into or out of other airports in Colorado. They only care about DEN flights.
library(tidyverse)
COflights <- read_csv("https://files.osf.io/v1/resources/3z5as4pej8/providers/osfstorage/5a8ca28f57103100104584db")
view(COflights)

#flight that originate from DEN 
denflightsOri <-filter(COflights, ORIGIN %in% c("DEN"))
view(denflightOri)

#flight that its destination is DEN
DenflightDest<-filter(COflights, DEST %in% c("DEN"))

#flifht that both orginate and arrive at DEN # *update*
DENfights<-filter(COflights, DEST == "DEN")

view(DENfights)

# delayed, flight that arrives 15 minutes or more from shedualed time

lateflights<-filter(DENfights, ARR_DELAY >= 15)

# early, On-time means any flight arriving early or within 14 minutes 
earlyflights<-filter(DENfights, ARR_DELAY <= 14)

#count of flight that arrives 15 minutes or more from shedual time
(countLate<-count(lateflights))

#count of flight arriving early or within 14 minutes 
(countEarly<-count(earlyflights))

#total count of flight that that arrived in DEN
Countotal<-count(DENfights)

#the Percentage of flights that arrived early 
(percOfearlyflight<-countEarly/Countotal*100)
    # 83.46712 %

#the Percentage of flights that arrived late 
(percOflateflight<-countLate/Countotal*100)
    # 15.65756


#------analysing months 

#------Late arrivals 
ggplot(data = lateflights) +
  geom_histogram(mapping = aes(x = MONTH), binwidth = .1 )

#it seems that months that are closer to international holidays or vacations tend to have a higher percentage of flights that are late  
#       thus, JAN, MAY, JUNE, JULY, AGU (august), and DEC (dicember) have the highest acounts flights arriving late. 


#lets take a closer look 
#jan 
(JANArrLate<-filter(lateflights, MONTH %in% c(1)))
#persentage of flights that where late in JAN in all the flight that where late 
(perJANarrLate<-count(JANArrLate)/countLate)
#we can see that late flights in JAN make a significant percentage of all lfights that where late (10%)
(perJANarrLateTotal<-count(JANArrLate)/Countotal)
#similarly we can see that from all the flight flight in JAN had a 1.7 percent chance of being late. 


#May
(MAYArrLate<-filter(lateflights, MONTH %in% c(5)))
#persentage of flights that where late in MAY in all the flight that where late 
(perMAYarrLate<-count(MAYArrLate)/countLate)
#we can see that late flights in MAY make a significant percentage of all lfights that where late (9%)
(perMAYarrLateTotal<-count(MAYArrLate)/Countotal)
#similarly we can see that from all the flight flight in MAY had a 1.5 percent chance of being late. 

#June
(JUNArrLate<-filter(lateflights, MONTH %in% c(6)))
#persentage of flights that where late in JUN in all the flight that where late 
(perJUNarrLate<-count(JUNArrLate)/countLate)
#we can see that late flights in JUN make a significant percentage of all lfights that where late (9.9%)
(perJUNarrLateTotal<-count(JUNArrLate)/Countotal)
#similarly we can see that from all the flight flight in JUN had a 1.7 percent chance of being late. 

#July
(JULYArrLate<-filter(lateflights, MONTH %in% c(7)))
#persentage of flights that where late in JUN in all the flight that where late 
(perJULYarrLate<-count(JULYArrLate)/countLate)
#we can see that late flights in JULY make a significant percentage of all fights that where late (10.8%)
(perJULYarrLateTotal<-count(JULYArrLate)/Countotal)
#similarly we can see that from all the flight flight in JULY had a 1.7 percent chance of being late.

#August
(AUGArrLate<-filter(lateflights, MONTH %in% c(8)))
#persentage of flights that where late in AUG in all the flight that where late 
(perAUGarrLate<-count(AUGArrLate)/countLate)
#we can see that late flights in AUG make a significant percentage of all fights that where late (11.2%)
(perAUGarrLateTotal<-count(AUGArrLate)/Countotal)
#similarly we can see that from all the flight flight in AUG had a 1.75 percent chance of being late.

#December 
(DICArrLate<-filter(lateflights, MONTH %in% c(12)))
#persentage of flights that where late in DEC in all the flight that where late 
(perDICarrLate<-count(DICArrLate)/countLate)
#we can see that late flights in DEC make a significant percentage of all fights that where late (9.3%)
(perDICarrLateTotal<-count(DICArrLate)/Countotal)
#similarly we can see that from all the flight flight in DEC had a 1.4 percent chance of being late.

((perDICarrLateTotal+perAUGarrLateTotal+perJULYarrLateTotal+perJUNarrLateTotal+perMAYarrLateTotal)/5)
#we can observe that within these month flights to denver have on ave a 1.6 percent chance of being late 


#feb, march, april, sep, oct, and nov all have less chance of flights arriving late.

#FEB
(FEBArrLate<-filter(lateflights, MONTH %in% c(2)))
#persentage of flights that where late in FEB in all the flight that where late 
(perFEBarrLate<-count(FEBArrLate)/countLate)
#we can see that late flights in FEB make a less significant percentage of all fights that where late (6.17%)
(perFEBarrLateTotal<-count(FEBArrLate)/Countotal)
#similarly we can see that from all the flight flight in FEB had a 0.1 percent chance of being late.

#March
(MARarrLate<-filter(lateflights, MONTH %in% c(3)))
#persentage of flights that where late in March in all the flight that where late 
(perMARarrLate<-count(MARarrLate)/countLate)
#we can see that late flights in March make a less significant percentage of all fights that where late (8.64%)
(perMARarrLateTotal<-count(MARarrLate)/Countotal)
#similarly we can see that from all the flight flight in March had a 1.35 percent chance of being late.

#April
(APRarrLate<-filter(lateflights, MONTH %in% c(4)))
#persentage of flights that where late in April in all the flight that where late 
(perAPRarrLate<-count(APRarrLate)/countLate)
#we can see that late flights in April make a less significant percentage of all fights that where late (6.98%)
(perAPRarrLateTotal<-count(APRarrLate)/Countotal)
#similarly we can see that from all the flight flight in April had a 1.09 percent chance of being late.

#September
(SEParrLate<-filter(lateflights, MONTH %in% c(9)))
#persentage of flights that where late in September in all the flight that where late 
(perSEParrLate<-count(SEParrLate)/countLate)
#we can see that late flights in September make a less significant percentage of all fights that where late (5.56%)
(perSEParrLateTotal<-count(SEParrLate)/Countotal)
#similarly we can see that from all the flight flight in September had a 0.8 percent chance of being late.

#October 
(OCTarrLate<-filter(lateflights, MONTH %in% c(10)))
#persentage of flights that where late in October in all the flight that where late 
(perOCTarrLate<-count(OCTarrLate)/countLate)
#we can see that late flights in October make a less significant percentage of all fights that where late (7.04%)
(perOCTarrLateTotal<-count(OCTarrLate)/Countotal)
#similarly we can see that from all the flight flight in October had a 1.1 percent chance of being late.

#november 
(NOVarrLate<-filter(lateflights, MONTH %in% c(11)))
#persentage of flights that where late in november in all the flight that where late 
(perNOVarrLate<-count(NOVarrLate)/countLate)
#we can see that late flights in november make a less significant percentage of all fights that where late (4.18%)
(perNOVarrLateTotal<-count(NOVarrLate)/Countotal)
#similarly we can see that from all the flight flight in november had a 0.65 percent chance of being late. the lowest of all the month for arrving late. 

#--------------early Arivals 
ggplot(data = earlyflights) +
  geom_histogram(mapping = aes(x = MONTH), binwidth = .1 )

#it seems that flight that are between the march and november have the lowest counts of early arrivals. 
#it is hard to tell as to why this might be happening however, weather around this time a year in denver has more snowfall than the rest of the yaer which affects airport trafic. 
#maybe there is a positive corralation between flights being less early and taxi out during this time a year.  

#-----end months 

#---working with distance, looking for diffrances in flight that avravied early and late in DEN

ggplot(data = earlyflights) +
  geom_histogram(mapping = aes(x = DISTANCE), binwidth = 20 )

ggplot(data = lateflights) +
  geom_histogram(mapping = aes(x = DISTANCE), binwidth = 20 )

ggplot(data = earlyflights, mapping = aes(x = ARR_DELAY, y = DISTANCE)) +
  geom_boxplot()

# visualy the box plot does not display any diffrancs 

(mean(earlyflights$ARR_DELAY))
(MeanEaDist<-mean(earlyflights$DISTANCE))

#most flights that avired early did so on ave with a distance of 895.3668 miles and 10 mins ealry  (-10 min)

mean(lateflights$ARR_DELAY)
(MaenLaDist<-mean(lateflights$DISTANCE))

ggplot(data = lateflights, mapping = aes(x = ARR_DELAY, y = DISTANCE)) +
  geom_boxplot()
#most flights that avired late did so on ave given ave distance of 922.6956 miles and 62 mins late on ave

#so it seems that is an intercation somewhere between 895.3668 and 922.6956 miles that may cause flight to be delayed on ave
#using the midpoint to see in there is if traveling more or less distance 
count(lateflights)
LateGrater<-filter(lateflights, DISTANCE >= 909.031 )
(LG<-count(LateGrater))
LateLesser<-filter(lateflights, DISTANCE <= 909.031 )
(LL<-count(LateLesser))

count(earlyflights)
earlyGrater<-filter(earlyflights, DISTANCE >= 909.031 )
(EG<-count(earlyGrater))
earlyLesser<-filter(earlyflights, DISTANCE <= 909.031 )
(EL<-count(earlyLesser))

#getting persentages 
#percengated of flight that where early that travals >= 909.031
(EG/countEarly*100)
#percengated of flight that where late that travals <= 909.031
(EL/countEarly*100)

#percengated of flight that where late that travals >= 909.031
(LG/countLate*100)
#percengated of flight that where late that travals <= 909.031
(LL/countLate*100)

#it seems that in both conditions (late and early arrivals) percentage difrance in flights that flew to DEN with a distance grater and lesser than 909.031 don't differ
#thus, flights that flew less than 909.031 tended to both more late and ealry. this is probably because most flights to DEN fly under 900 miles. 
```

###end Jorge 
